FROM alpine:3.19

WORKDIR /root

RUN apk add --no-cache \
    frr \
    busybox \
    iproute2 \
    iputils \
    bash \
    frr-openrc\
    tcpdump \
    vim \
    busybox-extras\
    tini 

COPY /scripts  /scripts
    
RUN chmod +x /scripts/* -R
    
ENTRYPOINT ["/sbin/tini", "--"]

