FROM alpine:3.19

# All tools in one single layer — zero tolerance for missing packages
RUN apk add --no-cache \
    bash \
    busybox \
    iproute2 \
    iputils 

WORKDIR /root

COPY /scripts  /scripts
    
RUN chmod +x /scripts/* -R

CMD ["/bin/bash"]
